# Lab 2: Some Games

**Done By:**
- Name: Sudip Parajuli
- Roll: PUR077BEI041
- Faculty: BEI

**Submitted To:**
- Name: Pukar Karki
- Department of Electronics and Computer Engineering 
- IOE Purwanchal Campus, Dharan

# Suduko Problem

In [13]:
import numpy as np

#giving a sudoku board problem
board = [[5, 3, 0, 0, 7, 0, 0, 0, 0],
         [6, 0, 0, 1, 9, 5, 0, 0, 0],
         [0, 9, 8, 0, 0, 0, 0, 6, 0],
         [8, 0, 0, 0, 6, 0, 0, 0, 3],
         [4, 0, 0, 8, 0, 3, 0, 0, 1],
         [7, 0, 0, 0, 2, 0, 0, 0, 6],
         [0, 6, 0, 0, 0, 0, 2, 8, 0],
         [0, 0, 0, 4, 1, 9, 0, 0, 5],
         [0, 0, 0, 0, 8, 0, 0, 7, 9]]

solved = False  # Flag to indicate if the solution is found

def is_possible(row, col, number):
    """
    Returns True if the given number can be placed at the given row and column
    """
    global board
    for x in range(9):
        if board[row][x] == number or board[x][col] == number:
            return False

    x0 = (row // 3) * 3
    y0 = (col // 3) * 3
    for i in range(3):
        for j in range(3):
            if board[x0 + i][y0 + j] == number:
                return False
    return True

def solve():
    """
    Solves the Sudoku board using backtracking
    """
    global board, solved
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                for number in range(1, 10):
                    if is_possible(i, j, number):
                        board[i][j] = number
                        # Recursively solve the rest of the board
                        solve()
                        if solved:
                            return
                        # If the solution is not found, backtrack
                        board[i][j] = 0
                return
    print(np.matrix(board))
    solved = True

solve()
if not solved:
    print("No solution found.")


[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


## Bot Saved Princess Problem

In [1]:
def displayPathtoPrincess(n, grid):
    posM = []
    posP = []

    # Find positions of 'm' and 'p'
    for x in range(n):
        for y in range(n):
            if grid[x][y] == 'm':
                posM = [x, y]
            elif grid[x][y] == 'p':
                posP = [x, y]

    Mx, My = posM
    Px, Py = posP

    # Determine vertical moves
    while Mx != Px:
        if Mx > Px:
            print("UP")
            Mx -= 1
        elif Mx < Px:
            print("DOWN")
            Mx += 1

    # Determine horizontal moves
    while My != Py:
        if My > Py:
            print("LEFT")
            My -= 1
        elif My < Py:
            print("RIGHT")
            My += 1
        
# Add dummy input
m = 3
grid = [
    "--m",
    "---",
    "p--"
]

displayPathtoPrincess(m, grid)

DOWN
DOWN
LEFT
LEFT
