# Lab 2: Some Games

**Done By:**
- Name: Sudip Parajuli
- Roll: PUR077BEI041
- Faculty: BEI

**Submitted To:**
- Name: Pukar Karki
- Department of Electronics and Computer Engineering 
- IOE Purwanchal Campus, Dharan

## Crypto Arithmetic Problem

In [1]:
# Internet Copied need to do this with genetic algorithm
from itertools import permutations

digits=[0,1,2,3,4,5,6,7,8,9]
word1 = "LOGIC"
word2 = "LOGIC"
word3 = "PROLOG"
mapped_output = {}


def word_to_number(word):
    number = 0
    for i in range(len(word)):
        number = number*10 + mapped_output[word[i]]
    return number

def check_solution():
    if word_to_number(word1) + word_to_number(word2) == word_to_number(word3):
        return True
    return False


def solve_cryptarithmetic():
    global mapped_output
    letters = set(word1 + word2 + word3)  # Collect all unique letters
    if len(letters) > 10:  # If there are more than 10 unique letters, it's unsolvable
        return False

    for perm in permutations(digits, len(letters)):
        mapped_output = dict(zip(letters, perm))

        # Convert the first letter of each word to ensure it's not mapped to 0
        if mapped_output[word1[0]] == 0 or mapped_output[word2[0]] == 0 or mapped_output[word3[0]] == 0:
            continue

        if check_solution():
            print(f"Solution found: {mapped_output}")
            print(f"{word1} = {word_to_number(word1)}, {word2} = {word_to_number(word2)}, {word3} = {word_to_number(word3)}")
            return True

    print("No solution found.")
    return False

solve_cryptarithmetic()


Solution found: {'L': 9, 'R': 8, 'C': 2, 'G': 4, 'P': 1, 'O': 0, 'I': 5}
LOGIC = 90452, LOGIC = 90452, PROLOG = 180904


True

# Suduko Problem

In [13]:
import numpy as np

board = [[5, 3, 0, 0, 7, 0, 0, 0, 0],
         [6, 0, 0, 1, 9, 5, 0, 0, 0],
         [0, 9, 8, 0, 0, 0, 0, 6, 0],
         [8, 0, 0, 0, 6, 0, 0, 0, 3],
         [4, 0, 0, 8, 0, 3, 0, 0, 1],
         [7, 0, 0, 0, 2, 0, 0, 0, 6],
         [0, 6, 0, 0, 0, 0, 2, 8, 0],
         [0, 0, 0, 4, 1, 9, 0, 0, 5],
         [0, 0, 0, 0, 8, 0, 0, 7, 9]]

solved = False  # Flag to indicate if the solution is found

def is_possible(row, col, number):
    """
    Returns True if the given number can be placed at the given row and column
    """
    global board
    for x in range(9):
        if board[row][x] == number or board[x][col] == number:
            return False

    x0 = (row // 3) * 3
    y0 = (col // 3) * 3
    for i in range(3):
        for j in range(3):
            if board[x0 + i][y0 + j] == number:
                return False
    return True

def solve():
    """
    Solves the Sudoku board using backtracking
    """
    global board, solved
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                for number in range(1, 10):
                    if is_possible(i, j, number):
                        board[i][j] = number
                        solve()
                        if solved:
                            return
                        board[i][j] = 0
                return
    print(np.matrix(board))
    solved = True

solve()
if not solved:
    print("No solution found.")


[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


## Bot Saved Princess Problem

In [3]:
def displayPathtoPrincess(n, grid):
    posM = []
    posP = []

    # Find positions of 'm' and 'p'
    for x in range(n):
        for y in range(n):
            if grid[x][y] == 'm':
                posM = [x, y]
            elif grid[x][y] == 'p':
                posP = [x, y]

    Mx, My = posM
    Px, Py = posP

    # Determine vertical moves
    while Mx != Px:
        if Mx > Px:
            print("UP")
            Mx -= 1
        elif Mx < Px:
            print("DOWN")
            Mx += 1

    # Determine horizontal moves
    while My != Py:
        if My > Py:
            print("LEFT")
            My -= 1
        elif My < Py:
            print("RIGHT")
            My += 1
        
# Add dummy input
m = 3
grid = [
    "--m",
    "---",
    "-p-"
]

displayPathtoPrincess(m, grid)

DOWN
DOWN
LEFT
